model:
  base_learning_rate: 1e-6
  target: specvqgan.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 128
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 1712 #848
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [53]
      dropout: 0.0

    lossconfig:
      target: specvqgan.modules.losses.vqperceptual.VQLPAPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 1
        disc_start: 2001
        disc_weight: 0.8
        codebook_weight: 1.0
        min_adapt_weight: 1.0
        max_adapt_weight: 1.0
        perceptual_weight: 1.0

lightning:
  callbacks:
    image_logger:
      target: train.ImageLogger
      params:
        for_specs: True
        vocoder_cfg:
          target: train.VocoderMelGan
          params:
            ckpt_vocoder: './vocoder/logs/asmr-by-material/'
  trainer:
    sync_batchnorm: true

data:
  target: train.SpectrogramDataModuleFromConfig
  params:
    batch_size: 2  #3
    num_workers: 8

    spec_dir_path: '/juno/u/jyau/regnet/data/features/ASMR/orig_asmr_by_material_clips/melspec_10s_44100hz/'
    sample_rate: 44100
    mel_num: 80
    spec_len: 1720
    spec_crop_len: 1712 # 848, 1712
    random_crop: False

    train:
      target: specvqgan.data.vas.VASSpecsTrain
      params:
        specs_dataset_cfg:
          split_path: '/juno/u/jyau/regnet/filelists/asmr_by_material_train.txt'
          dataset_type: "asmr"
    validation:
      target: specvqgan.data.vas.VASSpecsValidation
      params:
        specs_dataset_cfg:
          split_path: '/juno/u/jyau/regnet/filelists/asmr_by_material_test.txt'
          dataset_type: "asmr"
